### ISSUE TITLE
check_rmsThresh when OSTs are inaccurate

### ISSUE THREAD

**Issue by rpkarlin** [carrien/free-speech#102]
As currently written, check_rmsThresh will look at mean RMS between OST status 2 and 4 if a status 4 exists. Thus, for things like measureFormants, the RMS threshold check will look at the mean RMS between status 2 and 4. 

Normally this is okay but we had a participant today that spoke very loudly (sp728, hearingLossAAF). The word in the check LPC section was "head"; for the vast majority of their trials, they triggered both status 2 and 4 during /b/ due to prevoicing. The default trigger for vowel onset in measureFormants is RMS >= 0.01 for 50 ms; status 4 is triggered by negative slope (i.e. decreasing RMS). Because status 2-4 were entirely on /b/, and the RMS of /b/ did not reach 0.03 as the mean (the threshold required by run_checkLPC), the participant got messages to speak louder (and did---when I got there they were speaking VERY loudly). Example trial: 

![image](https://github.com/carrien/free-speech/assets/51800173/94447124-34eb-4e53-9f07-471de3b95894)

Short of totally changing how check_rmsThresh works (like going back to peak for everything), I have two suggestions which should work for a LOT of cases but likely not all: 

1. Make the threshold for triggering measureFormants' OST 2 higher, closer to the threshold. This would make you less likely to trigger statuses in little RMS blips that wouldn't hit mean RMS requirements. 

This probably won't be a reliable fix. For speakers such as this one, prevoicing can get VERY loud. For example, this trial's /b/ voicing peaks at RMS = 0.07. So well above the threshold for a good trial before the vowel even starts. This means that they would have gotten a "speak louder" message anyway. (It's also loud for quite long; even setting the duration parameter to 0.07 only works for about half the trials) 

![image](https://github.com/carrien/free-speech/assets/51800173/9232cef9-d63f-4d88-a095-491cf6fbe033)

This speaker was also speaking pretty loudly even at the very beginning, so it wasn't just the result of following instructions to speak louder. Happy to talk about potential outlier nature of this speaker off github. But I've had some difficulty with older speakers of English as well, who are more likely to prevoice (along with Southern Am English speakers and AAVE speakers). 

2. Change measureFormants default to using INTENSITY_AND_RATIO_ABOVE_THRESH for status 2. Requiring a higher RMS AND higher ratio means that you'll largely disregard prevoicing. Examples with current default: 

![image](https://github.com/carrien/free-speech/assets/51800173/30c0c8db-bc5f-4945-a7d1-cbebca1011dc)

Examples with suggested default (tweaking specific values may be helpful; these are the defaults I use in taimComp for "guide" and "buy d..."). I know Chris and I have talked about this before and we were struggling to find parameters that worked more universally, so this might not be the best either. 

![image](https://github.com/carrien/free-speech/assets/51800173/2c94e0e9-d8d1-4efb-87a8-9497fc3faa80)

This affected how the formants were tracked in check_audapterLPC but that's not really a big deal in itself, since you can always change the OST tracking after the fact so that it grabs the vowel. The only real problem is that we're detecting vowels that aren't vowels and basing the "speak louder" message on that.

**Comment by cwnaber** [comment]
Making a note here that if we do find a good solution for this, that method might work well for determining **vowel duration** in our compensation studies that care about vowel duration, e.g., cerebAAF. Right now those studies use a similarly simple (but non-OST-based) method of using RMS thresholds for onset and offset, and considering everything in-between to be "vowel."

**Comment by cwnaber** [comment]
We essentially side-stepped this issue by abandoning a method of vowel detection that relies either on OSTs or RMS values in any way. We're just going to use things derived from the peak. See #104
